/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.lang.Math;
import java.lang.Math;
import java.util.*; //Import for Arrays and Scanner
import java.io.*; //Import for Scanner
import java.util.Arrays;
import java.util.Random;
import java.util.HashMap; // import the HashMap class
import java.util.List;
import java.util.ArrayList;

public class Library {
    public static void main(String[] args)
    {
        System.out.println(Arrays.toString(roll(4)));
        // testing code by print results
        String[] arr = {"1","2","5"};
        int[] newArr = {1,2,5};
        long[] chalArr = {1,2,6,7};
        int[][] arrOfArrays = {{1,2,3},{4,5,6},{10,1,2}};
        System.out.println(roll(5));
        System.out.println(containsDuplicates(arr));
        System.out.println(calculatingAverages(newArr));
        System.out.println(Arrays.toString(minAvg(arrOfArrays)));
    }

    // roll method
    public static int[] roll(int n){
       // declare the Arr;
       int[] arr = new int[n];
       // loop n time;
       for(int i = 0; i < n ;i++){
         //put random value to array
         arr[i] =(int) (Math.random() * 7);
       }
       // return arr;
       return arr;
    }

    // 2nd solution of Roll
    public static int[] roll2ndSolution(int n){
        // declare the Arr;
        int[] arr = new int[n];
        // loop n time;
        for(int i = 0; i < n ;i++){
            //put random value to array
            Random rand = new Random();
            arr[i] = rand.nextInt(6) +1;
        }
        // return arr;
        return arr;
    }

    // Method isCorrectOutput to test the return value or role => if the return value more than 0 and less than 6;
    public static boolean isCorrectOutput(int num){
        return  num < 7 && num > 0;
    };

    // Contains Duplicates first solution;
    public static boolean containsDuplicates (String[] arr){
        //I used the map to save the value of each index;
        HashMap<String, Integer> capitalCities = new HashMap<>();
        // loop threw the array;
       for(int i = 0; i < arr.length ; i++){
         // check if the value in the map.
         if(capitalCities.get(arr[i]) == null){
            // if value is not in the map add it
           capitalCities.put(arr[i], 1);
         }else{
             // else return true;
             return true;
         }
       }
       // return false if not returned true;
       return false;
      }
    // Contains Duplicates 2nd solution;
    public static boolean containsDuplicates2ndSol (String[] arr){
        // loop threw array;
        for(int i = 0 ; i < arr.length ; i++){
            // loop threw array after i;
            for(int j = i+1 ; j < arr.length ; j++){
                // check the element of i if it is equal the element of j return true;
                if(arr[i] == arr[j]){
                    return true;
                }
            }
        }
        // return false if not returned true;
        return false;
    }

    // Contains Duplicates 3rd solution;
    public static boolean containsDuplicates3rdSol (String[] arr){
        // make a list from the array;
        List<String> list = new  ArrayList<String>();
        // loop threw array;
        for(int i = 0; i < arr.length ; i++){
            // if list contains the item return true
            if(list.contains(arr[i]) == true){
                return true;
            }else{
                //else add the element to the list;
                list.add(arr[i]);
            }
        }
        // return false if not returned true;
        return false;
    }

    // Calculating Averages solution;
    public static double calculatingAverages (int[] arr){
        //declare double var
        double sum = 0;
        // loop threw array;
        for(int i = 0 ; i < arr.length ; i++){
            // sum all array value;
            sum += arr[i];
        }
        // return the avg;
        return (sum/arr.length);
    }

    // Min Avg solution;
    public static int[] minAvg (int[][] arr){
        //declare double var to store the min value => defolt value first Avg;
        double minArr = calculatingAverages(arr[0]);
        // declare array to store the array of min avg => defult value first arr;
        int[] returnArr = arr[0];
        // loop threw array;
        for(int i = 0 ; i < arr.length ; i++){
            //declare double var to store corrant array Avg;
            double arrAvg = calculatingAverages(arr[i]);
            // check the average => if the corrant array Avg less the the minArr change the value of minArr and returnArr;
            if(minArr > arrAvg){
                minArr = arrAvg;
                returnArr = arr[i];
            }
        }
        return returnArr;
    };
}
