/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("anything",4,3.7);
        System.out.println(restaurant.toString());

        Review review = new Review("anything","anything",3);
//        System.out.println(review.toString());
        restaurant.addReview(review);
        System.out.println(review.toString());
        System.out.println(restaurant.toString());
    }
}
