/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.nio.file.Files;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.BufferedReader;
import java.io.IOException;

public class App {
    public static void main(String[] args) {
        System.out.println(readFile("gates.js"));
    }

    public static String readFile (String pathNew){
        Path path = Paths.get(pathNew);

        BufferedReader reader = null;
        try {
            reader = Files.newBufferedReader(path);
            String line = reader.readLine();
            int count = 0;
            String outPut = "";
            while(line != null){
                count++;
                int length = line.length();
                if(length != 0 &&  line.substring(length - 1).equals(";") == false && line.substring(length - 1).equals("}") == false && line.substring(length - 1).equals("{") == false && line.contains("if") == false && line.contains("else") == false) {
                    outPut += "Line" +count+": Missing emicolon."+"\n";
                }
                line = reader.readLine();
            }
            return outPut;
        } catch (IOException ex){
            ex.printStackTrace();
            return "error";
        } finally {
            if(reader != null) {
                try {
                    reader.close();
                } catch(IOException e){
                    System.out.println("an error occurred while closing the file");
                }
            }
        }
    }
}
