/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.nio.file.Files;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.BufferedReader;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        readFile();
    }

    public static void readFile (){
        Path path = Paths.get("gates.js");

        BufferedReader reader = null;
        // option 2
        try {
            reader = Files.newBufferedReader(path);
            String line = reader.readLine();
            int count = 0;
            while(line != null){
                count++;
                int length = line.length();
                if(length != 0 &&  line.substring(length - 1).equals(";") == false && line.substring(length - 1).equals("}") == false && line.substring(length - 1).equals("{") == false && line.contains("if") == false && line.contains("else") == false) {
                    System.out.println("Line" +count+": Missing emicolon.");
                }
                line = reader.readLine();
            }
        } catch (IOException ex){
            ex.printStackTrace();
        } finally {
            if(reader != null) {
                try {
                    reader.close();
                } catch(IOException e){
                    System.out.println("an error occurred while closing the file");
                }
            }
        }
    }
}
